// Code generated by go:generate; DO NOT EDIT.

// Generated with command: go generate
// (from the project root)

package modules

import (
	_ "github.com/GoMudEngine/GoMud/modules/auctions"
	_ "github.com/GoMudEngine/GoMud/modules/follow"
	_ "github.com/GoMudEngine/GoMud/modules/gmcp"
	_ "github.com/GoMudEngine/GoMud/modules/leaderboards"
	_ "github.com/GoMudEngine/GoMud/modules/time"
)
