// Code generated by go:generate; DO NOT EDIT.

// Generated with command: go generate
// (from the project root)

package modules

import (
	"fmt"
	"os"
)

func init() {
	fmt.Println("!!! Run \"go generate\" before building this project !!!")
	os.Exit(1)
}